name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies on macOS
        run: |
          set -x
          brew install shellcheck python3
          pip3 install pyflakes
          shellcheck --version
          pyflakes --version
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install dependencies on Linux
        run: |
          set -x
          sudo apt install shellcheck
          pip install pyflakes
          shellcheck --version
          pyflakes --version
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install dependencies on Windows
        run: |
          # `choco install shellcheck` is too slow on GitHub Actions. It takes more than 3 minutes to install one package
          # choco install shellcheck
          pip install pyflakes
          pyflakes --version
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build ./cmd/actionlint
        env:
          # Note: -race requires cgo
          CGO_ENABLED: 0
      - run: go test -v -race -coverprofile coverage.txt -covermode=atomic
      # Dog fooding 🐶
      - run: ./actionlint
      - uses: codecov/codecov-action@v1
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get honnef.co/go/tools/cmd/staticcheck@latest
      - name: Add staticcheck to PATH
        run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: staticcheck ./...
