name: Download script
on:
  push:
    paths:
      - 'scripts/download-actionlint.bash'
  pull_request:
    paths:
      - 'scripts/download-actionlint.bash'
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  download:
    name: Test download script
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
        id: get_actionlint
      - name: Run actionlint
        run: ${{ steps.get_actionlint.outputs.executable }} -help
        shell: bash
