name: Problem Matchers
on:
  push:
    paths:
      - 'scripts/generate-actionlint-matcher/object.js'
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  matcher-test:
    name: Test generate-actionlint-matcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Test actionlint-matcher.json
        run: node ./scripts/generate-actionlint-matcher/test.js
      - name: Ensure .github/actionlint-matcher.json is up-to-date
        run: |
          make .github/actionlint-matcher.json
          if git diff --quiet; then
            echo 'OK'
          else
            echo 'NOT OK'
            set -x
            git diff
            exit 1
          fi
