name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone nested repository to make version bump commit
        uses: actions/checkout@v2
        with:
          path: ./tmp-actionlint-for-update-ver
          ref: main
          fetch-depth: 0
      - name: Update versions in sources
        run: |
          cd ./tmp-actionlint-for-update-ver
          bash ./scripts/update-download-actionlint.bash "${GITHUB_REF#refs/tags/v}"
          rm -rf ./tmp-actionlint-for-update-ver
      - uses: actions/setup-go@v2
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check the download script works after release
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
